- my-app/src/components/cartItem/CartItem.tsx
https://app.clickup.com/t/8693qpauk
> [UI]: Cart item layout

- my-app/src/components/productVariantsActions/ProductVariantsActions.tsx
- my-app/src/types/Phone.ts
https://app.clickup.com/t/8693qpaqz
> [UI]: Variants/acions block layout. Information and working add to cart

- my-app/package.json
- my-app/src/components/pages/PhonePage/PhonePage.tsx
- my-app/src/utils/fetchHelper.ts
https://app.clickup.com/t/8693qpavm
I would like to have every component for this page first before fixing 
todos
> [UI]: Page route and base layout

- my-app/package.json
- my-app/src/components/pages/PhonePage/PhonePage.tsx
- my-app/src/utils/fetchHelper.ts
- server/migrations/20240208113833-create-phone.js
- server/seeders/20240208122627-Phone.js
- server/seeders/20240208123309-Product.js
> Fix fixing seeder

- server/src/controller/phone.controller.ts
- server/src/router/phone.router.ts
- server/src/service/phone.service.ts
task: https://app.clickup.com/t/8693qpat8
`phones/phoneId/recommended` gives you 5 recommended phones, searched by model and color
> feat: implement /products/:id/recommended endpoint

- server/src/controller/phone.controller.ts
- server/src/router/phone.router.ts
- server/src/types/sortType.ts
https://app.clickup.com/t/8693v5bnr
> [API]: Hot prices controller

- my-app/src/theme/theme.tsx
Added typography  mobile h1-h4
> Favorits page

- server/migrations/20240218123914-create-tablet.js
- server/migrations/20240218123941-create-accessory.js
- server/models/accessory.js
- server/models/tablet.js
- server/seeders/20240218124201-Tablet.js
- server/seeders/20240218124211-Accessory.js
- server/src/model/accessory.model.ts
- server/src/model/tablet.model.ts
- server/src/utils/db.ts
https://app.clickup.com/t/8693vd937
> Added tablets, and accossories to databases with a seeder

- my-app/src/components/pages/FavouritesPage.tsx
> fix: added isLoading state for every item

- my-app/src/components/pages/HomePage.tsx
https://app.clickup.com/t/8693qparz
> [UI]: Hot prices section

- server/main.ts
- server/seeders/20240218124211-Accessory.js
- server/src/controller/accessory.controller.ts
- server/src/controller/product.controller.ts
- server/src/controller/tablet.controller.ts
- server/src/model/accessory.model.ts
- server/src/model/phone.model.ts
- server/src/model/tablet.model.ts
- server/src/router/accessory.router.ts
- server/src/router/products.router.ts
- server/src/router/tablet.router.ts
- server/src/service/accessory.service.ts
- server/src/service/products.service.ts
- server/src/service/tablet.service.ts
- server/src/utils/db.ts
https://app.clickup.com/t/8693qpaw3
> Api add product type querry modify routes

- my-app/src/components/pages/PhonePage/PhonePage.tsx
- my-app/src/utils/fetchHelper.ts
https://app.clickup.com/t/8693qpatm
> Added carousel commponent to phonePage, fetched data from phone endpoint

- my-app/src/App.tsx
- my-app/src/components/pages/PhonePage/PhonePage.tsx
[task](https://app.clickup.com/t/8693vm3h8)
> UI fix product gallery length to match image number

- my-app/src/components/carousel/Carousel.tsx
- my-app/src/components/pages/PhonePage/PhonePage.tsx
- my-app/src/components/productCard/productCard.tsx
> Update: add justify-content to Product Card

- my-app/src/App.tsx
- my-app/src/components/catalog/Catalog.tsx
- my-app/src/components/header/Header.tsx
- my-app/src/components/layout/Layout.tsx
- my-app/src/components/pages/AccesoriesPage.tsx
- my-app/src/components/pages/FavouritesPage.tsx
- my-app/src/components/pages/PhonePage/PhonePage.tsx
- my-app/src/components/pages/TabletsPage.tsx
- my-app/src/components/productCard/productCard.tsx
- my-app/src/components/productCart/ProductCart.tsx
- my-app/src/types/ProductCartType.ts
- my-app/src/utils/fetchHelper.ts
8693vevcf: 8693vkvhb: 8693vkv4j: styled header onscroll, added navigate
https://github.com/PL-FE-SEP23-JANUSZ3X/product_catalog/assets/147045521/542ed27a-28bf-457c-bcc8-3bf9cebc2809
> Step 6 fixes

- server/src/controller/product.controller.ts
- server/src/router/products.router.ts
- server/src/service/products.service.ts
https://app.clickup.com/t/8693qpavj
> Added new endpoint for product search request

- my-app/src/components/carousel/Carousel.tsx
- my-app/src/components/pages/CartPage.tsx
- my-app/src/components/pages/FavouritesPage.tsx
- my-app/src/components/productCard/productCard.tsx
- my-app/src/components/productCart/ProductCart.tsx
- my-app/src/components/productCart/ProductCart.types.ts
- my-app/src/components/slider/Slider.tsx
- my-app/src/types/ProductCartType.ts
- my-app/src/utils/getRandomKey.ts
> Local store fix

- my-app/src/components/footer/Footer.tsx
> fix: changed width for footer, fixed style for link

- my-app/src/components/header/Header.tsx
- my-app/src/components/searchDrawer/SearchDrawer.tsx
> [UI]: search component

- my-app/src/components/carousel/Carousel.tsx
- my-app/src/components/customIconButtons/CustomIconButton.tsx
- my-app/src/components/customIconButtons/index.ts
> [UI]: Added custom IconButton Arrows component

- my-app/src/types/OrderDataType.ts
- my-app/src/types/OrderProductType.ts
- server/main.ts
- server/src/controller/accessory.controller.ts
- server/src/controller/order.controller.ts
- server/src/model/order.model.ts
- server/src/router/order.router.ts
- server/src/service/order.service.ts
- server/src/utils/db.ts
https://app.clickup.com/t/8693w07t9
> Added order mvc, database

- my-app/src/components/searchDrawer/SearchDrawer.tsx
- my-app/src/utils/fetchHelper.ts
Do not merge yet!
https://app.clickup.com/30346475/v/b/wy37b-31312
> UI Search functionality
